### ISSUE TITLE
[Q] Replacing existing files?

### ISSUE THREAD

**Issue by Kein** [hhyyrylainen/GodotPckTool#39]
There isnt info anywhere and all my attempts seems to have failed.
I want to replace a file inside a pck:
`Character/Player/Player.gdc`
however, no matter how I try to add it, it does not appear to be replacing original (or just fails), it just add new content to pck:
```
godotpcktool game.pck -a a Player.gdc
godotpcktool game.pck -a a Character/Player/Player.gdc
godotpcktool game.pck -a a ../Character/Player/Player.gdc
godotpcktool game.pck -a a res://Character/Player/Player.gdc
```

Is it supossed to be something obvious even a caveman can figure out, despite lack of docs?

**Comment by hhyyrylainen** [comment]
If you use the .pck content listing command, you should see the resulting paths inside the .pck file for each of the commands you tried. That should clarify what happened in each case. The add command assumes you already have the correct directory structure on your hard drive so that the file ends up with the correct path inside the pck in order to overwrite the file you want. Which a few of your attempts have, however you are missing `--remove-prefix` which is used in the example commands.

The main examples (in the main readme of this repo) show how, if you have a folder called `extracted` and starting from that folder the directory tree is exactly as you want within the pck, you can add and overwrite content.

So for example with this command:
```
godotpcktool Thrive.pck -a a extracted --remove-prefix extracted
```

And assuming you have a file like `extracted/some/folder/structure/image.png` then that will end up within the pck file with the prefix removed but the file path otherwise intact: `res://some/folder/structure/image.png`

That will also overwrite any pck entries that have the same path, so if there already was something in the pck file saved as `res://some/folder/structure/image.png` that is now overwritten.

Does that answer your question?

**Comment by hhyyrylainen** [comment]
Well the command line limit on Windows is either 8K or 32K characters, which is very easy to overshoot when rebuilding a pck file with a few hundred files and where full paths are specified. So for the script usage I use it for, it would likely blow up on Windows. And Windows is already enough of a pain to deal with.

> Any chance we can, uhh, have an extra switch that points to input JSON file got CLI usage?

It wouldn't be that hard to add a new flag like `--command-file` that would allow specifying a file to be passed to the JSON parsing part. So yeah it is possible that a feature like that could be added.

**Comment by hhyyrylainen** [comment]
I couldn't stop thinking about how to try to implement this and write the docs update, so I ended up doing it. Let me know if the readme is more clear now and if the JSON bulk API works for your usage. I'll upload the new version 2.1 right now.
